site_name: create-bindu-agent
repo_url: https://github.com/saptha-me/create-bindu-agent
site_url: https://saptha-me.github.io/create-bindu-agent
site_description: From idea to Internet of Agents in 2 minutes.
site_author: Raahul Dutta
edit_uri: edit/main/docs/
repo_name: saptha-me/create-bindu-agent
copyright: Maintained by Raahul Dutta.

nav:
  - Home: index.md
  - Features:
      - CI/CD with Github Actions: features/cicd.md
      - Linting & code quality: features/linting.md
      - Makefile: features/makefile.md
      - Dependency management with uv: features/uv.md
      - Publishing to PyPI: features/publishing.md
      - Testing with Pytest: features/pytest.md
      - Test coverage with codecov: features/codecov.md
      - Documentation with MkDocs: features/mkdocs.md
      - Containerization with Docker or Podman: features/docker.md
      - Devcontainer with VSCode: features/devcontainer.md
  - Tutorial: tutorial.md
  - Prompt Arguments: prompt_arguments.md
plugins:
  - search
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  feature:
    tabs: true
  palette:
    # Note: Using the system theme works with the insiders version
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#automatic-light-dark-mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: astral-light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: astral-dark
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/saptha-me/create-bindu-agent
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/create-bindu-agent/
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
